import "@/app/globals.css";
import Providers from "@/app/provider";
import Header from "@/app/roles/vendor_system/components/Header";
import AiChatbot from "@/app/roles/vendor_system/components/AiChatbot";
import { CopilotKit } from "@copilotkit/react-core/v2";
import "@copilotkit/react-core/v2/styles.css";

export const metadata = {
  title: "Specto (vendor)",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <Providers>
      <CopilotKit runtimeUrl="/api/copilotkit">
        <Header/>
        {children}
        <AiChatbot/>
      </CopilotKit>
    </Providers>
  );
}
