import "@/app/globals.css";
import Providers from "@/app/provider";
import Sidebar from "@/app/roles/vendor_system/dashboard/components/Sidebar";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <Providers>
        <Sidebar/>
        {children}
    </Providers>
  );
}
