import "./globals.css";
import Providers from "./provider";
import Script from "next/script";

export const metadata = {
  title: "Specto",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
    >
      <body className="min-h-full flex flex-col">
        <Providers>
          {children}
          <Script
            src="https://checkout.razorpay.com/v1/checkout.js"
            strategy="beforeInteractive"
          />
        </Providers>
      </body>
    </html>
  );
}
